package com.madnessfeed.frontend.model;

import io.quarkus.runtime.annotations.RegisterForReflection;

import lombok.Data;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@SuppressWarnings("serial")
@Schema(description = "Settings of a public page")
@Data
@RegisterForReflection
public class PublicPageSettings implements Serializable {

    @Schema(description = "id of the public page, empty to create a new page")
    private Long id;

    @Schema(description = "optional name of the public page, shown next to the application name")
    private String name;

    @Schema(description = "whether the public, read-only page is enabled", required = true)
    private boolean enabled;

    @Schema(
            description = "whether feeds that are not in any category are shown on the public page",
            required = true)
    private boolean showUncategorized;

    @Schema(
            description =
                    "secret token used in the address of the public page, generated by the server")
    private String token;

    @Schema(description = "ids of the categories shown on the public page", required = true)
    private List<Long> categoryIds = new ArrayList<>();
}
